J4de

high

# The `_claim` function catch an exception, causing the expected reversion in the Plugin contract not to happen

## Summary

The `_claim` function caught an exception, causing the expected reversion in the Plugin contract not to happen.

## Vulnerability Detail

The `_claim` function will call the claim fucntion of all Plugins, and catch the exceptions that occur in the Plugin contract, but it does not resolve the exception (only do emit). This caused some expected reversion within the Plugin contract not to occur.

Suppose the plugin implements the claim function like this:

```solidity
function claim(address account, address to, bytes calldata auxData)
	external override returns (uint256) {
	// ... skip
	uint256 rewards = getRewards(account);
	IERC20Upgradeable(tel).safeTransfer(to, exitAmount);
	
	// ... do some check
    require(valid);
    
    // clear transferred rewards
    setRewards(account, 0);
    return rewards;
}
```

In this case, if an exception occurs after the transfer, it may happen that the attacker has already claimed the reward, but the reward has not been cleared. The attacker can repeat the infinite number of times to claim the reward.

## Impact

Under some Plugin contracts, users may receive rewards repeatedly.

## Code Snippet

https://github.com/sherlock-audit/2023-02-telcoin/blob/main/telcoin-audit/contracts/staking/StakingModule.sol#L360-L366

## Tool used

Manual Review

## Recommendation

It is recommended not to catch exceptions or to avoid this risk in other ways.